1. Create a data file by using Python random module with different random generator
parameters. The data file must have 65000 X 10000 (rows X columns) in the data file. This
data file to be used as database for realization of math and matrix operations in cloud
computing lab assignments.

In [1]:
import numpy as np

In [2]:
import random

In [3]:
rows, columns = 65000, 10000
file_name = 'large_data_file.csv'

In [7]:
def generate_random_data(rows, cols):
 data = np.random.rand(rows, cols)
 return data

In [9]:
data = generate_random_data(rows, columns)

In [10]:
np.savetxt(file_name, data, delimiter=',', fmt='%.6f')

In [11]:
print(f'Data file "{file_name}" created with dimensions {rows} x {columns}.')

Data file "large_data_file.csv" created with dimensions 65000 x 10000.


2. Write a program in Python to assign subsequent rows to matrix first row elements.

In [12]:
import numpy as np

In [13]:
matrix = np.random.randint(1, 10, (5, 5))

In [14]:
result = {matrix[0, i]: matrix[1:, i] for i in range(matrix.shape[1])}

In [15]:
print("Original Matrix:")
print(matrix)
print("\nAssigned Subsequent Rows to First Row Elements:")
print(result)

Original Matrix:
[[7 7 2 2 5]
 [6 5 8 8 2]
 [5 6 6 3 3]
 [7 4 2 9 2]
 [4 2 6 2 6]]

Assigned Subsequent Rows to First Row Elements:
{7: array([5, 6, 4, 2]), 2: array([8, 3, 9, 2]), 5: array([2, 3, 2, 6])}


3. Write a program in Python to group similar elements into matrix

In [16]:
from collections import defaultdict
import numpy as np

In [17]:
matrix = np.random.randint(1, 5, (5, 5))  # Example matrix

In [18]:
grouped_elements = defaultdict(list)
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        grouped_elements[matrix[i, j]].append((i, j))

In [19]:
print("Original Matrix:")
print(matrix)

Original Matrix:
[[1 4 1 1 3]
 [3 1 3 3 4]
 [2 1 3 1 1]
 [1 2 3 3 4]
 [2 4 2 3 3]]


In [20]:
print("\nGrouped Elements:")
for key, value in grouped_elements.items():
    print(f"Element {key}: {value}")


Grouped Elements:
Element 1: [(0, 0), (0, 2), (0, 3), (1, 1), (2, 1), (2, 3), (2, 4), (3, 0)]
Element 4: [(0, 1), (1, 4), (3, 4), (4, 1)]
Element 3: [(0, 4), (1, 0), (1, 2), (1, 3), (2, 2), (3, 2), (3, 3), (4, 3), (4, 4)]
Element 2: [(2, 0), (3, 1), (4, 0), (4, 2)]


4. Write a program in Python to add and subtract matrices in python.

In [21]:
import numpy as np

In [22]:
matrix1 = np.random.randint(1, 10, (3, 3))  # Example matrix 1
matrix2 = np.random.randint(1, 10, (3, 3))  # Example matrix 2

In [23]:
addition = np.add(matrix1, matrix2)

In [24]:
subtraction = np.subtract(matrix1, matrix2)

In [25]:
print("Matrix 1:")
print(matrix1)

Matrix 1:
[[9 4 7]
 [5 4 4]
 [7 6 4]]


In [26]:
print("\nMatrix 2:")
print(matrix2)


Matrix 2:
[[1 3 1]
 [1 8 6]
 [7 5 7]]


In [27]:
print("\nAddition:")
print(addition)


Addition:
[[10  7  8]
 [ 6 12 10]
 [14 11 11]]


In [28]:
print("\nSubtraction:")
print(subtraction)


Subtraction:
[[ 8  1  6]
 [ 4 -4 -2]
 [ 0  1 -3]]


5. Write a program in Python to create an n x n square matrix, where all the sub-matrix has the
sum of opposite corner elements as even.

In [29]:
import numpy as np

In [30]:
def create_special_matrix(n):
    matrix = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            matrix[i, j] = (i + j) % 2
    return matrix

In [31]:
n = 4  # Example size
special_matrix = create_special_matrix(n)

In [32]:
print("Special Matrix:")
print(special_matrix)

Special Matrix:
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


6. Write a program in Python to perform row-wise element addition in tuple matrix.

In [33]:
tuple_matrix = [((1, 2), (3, 4)), ((5, 6), (7, 8)), ((9, 10), (11, 12))]

In [34]:
row_wise_addition = [tuple(sum(elements) for elements in row) for row in tuple_matrix]

In [35]:
print("Original Tuple Matrix:")
print(tuple_matrix)

Original Tuple Matrix:
[((1, 2), (3, 4)), ((5, 6), (7, 8)), ((9, 10), (11, 12))]


In [36]:
print("\nRow-wise Element Addition:")
print(row_wise_addition)


Row-wise Element Addition:
[(3, 7), (11, 15), (19, 23)]
